# Generated by Django 4.2.11 on 2025-02-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("食費", "食費"),
                            ("交通費", "交通費"),
                            ("住居費", "住居費"),
                            ("光熱費", "光熱費"),
                            ("娯楽費", "娯楽費"),
                            ("その他", "その他"),
                        ],
                        max_length=20,
                        verbose_name="カテゴリ",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="金額")),
                ("description", models.CharField(max_length=200, verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
            ],
        ),
    ]
